//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterWithSignupMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "First Name Is Required")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last Name Is Required")]
        public string LastName { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender Is Required")]
        public string gender { get; set; }
        [DisplayName("Age")]
        [Required(ErrorMessage = "Age Is Required")]
        public int age { get; set; }
        [DisplayName("Email")] 
        [Required(ErrorMessage = "Email Is Required")]

        public string email { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "User Name Is Required")]
        public string username { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Password Is Required")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm Password Is Required")]
        [DataType(DataType.Password)]
        [Compare("password",ErrorMessage = "Password Is Not Identical")]
        public string confirmpassword { get; set; }
    }
}
